const STUDY_TYPE = {
  READY: 'READY',
  PROGRESS: 'PROGRESS',
  COMPLETE: 'COMPLETE',
};

const JOIN_TYPE = {
  WAIT: 'WAIT',
  APPROVED: 'APPROVED',
  REFUSED: 'REFUSED',
};

const PROVIDER_TYPE = {
  KAKAO: 'KAKAO',
  GOOGLE: 'GOOGLE',
};

export { STUDY_TYPE, JOIN_TYPE, PROVIDER_TYPE };
